"""empty message

Revision ID: 04c1e2f6cc47
Revises: 1f4fceee46c7
Create Date: 2025-05-27 11:07:00.682981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04c1e2f6cc47'
down_revision: Union[str, None] = '1f4fceee46c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_user_answers', sa.Column('answers', sa.Text(), nullable=False))
    op.drop_column('test_user_answers', 'answer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_user_answers', sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('test_user_answers', 'answers')
    # ### end Alembic commands ###
