"""описание миграции2

Revision ID: 3a221e665ff4
Revises: 
Create Date: 2025-05-08 18:29:26.273981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a221e665ff4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_types', sa.Column('allow_multiple_passes', sa.Boolean(), nullable=False, comment='Можно ли проходить тест несколько раз'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_types', 'allow_multiple_passes')
    # ### end Alembic commands ###
