"""empty message

Revision ID: 52d27a83a90a
Revises: 04c1e2f6cc47
Create Date: 2025-05-29 20:08:05.719966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52d27a83a90a'
down_revision: Union[str, None] = '04c1e2f6cc47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_tokens', sa.Column('token_hash', sa.String(length=255), nullable=True, comment='Токен Telegram-бота'))
    op.drop_constraint('bot_tokens_token_key', 'bot_tokens', type_='unique')
    op.create_unique_constraint(None, 'bot_tokens', ['token_hash'])
    op.drop_column('bot_tokens', 'token')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='Является ли пользователь администратором'))
    op.add_column('bot_tokens', sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Токен Telegram-бота'))
    op.drop_constraint(None, 'bot_tokens', type_='unique')
    op.create_unique_constraint('bot_tokens_token_key', 'bot_tokens', ['token'])
    op.drop_column('bot_tokens', 'token_hash')
    # ### end Alembic commands ###
