"""empty message

Revision ID: 5515d67b38e6
Revises: 63344bff72f4
Create Date: 2025-05-30 01:04:04.480915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5515d67b38e6'
down_revision: Union[str, None] = '63344bff72f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_bots', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('user_bots', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('user_bots', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Дата удаления (если используется мягкое удаление)'))
    op.alter_column('user_bots', 'is_admin',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Является ли пользователь администратором',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_bots', 'is_admin',
               existing_type=sa.BOOLEAN(),
               comment='Является ли пользователь администратором',
               existing_nullable=True)
    op.drop_column('user_bots', 'deleted_at')
    op.drop_column('user_bots', 'updated_at')
    op.drop_column('user_bots', 'created_at')
    # ### end Alembic commands ###
