"""empty message

Revision ID: 63344bff72f4
Revises: 52d27a83a90a
Create Date: 2025-05-29 20:18:12.647633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63344bff72f4'
down_revision: Union[str, None] = '52d27a83a90a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bot_tokens_token_hash_key', 'bot_tokens', type_='unique')
    op.add_column('user_bots', sa.Column('is_admin', sa.Boolean(), nullable=True, comment='Является ли пользователь администратором'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_bots', 'is_admin')
    op.create_unique_constraint('bot_tokens_token_hash_key', 'bot_tokens', ['token_hash'])
    # ### end Alembic commands ###
