"""change telegram_bot_id to BigInteger

Revision ID: 71cea428a3f3
Revises: b1f6f69e7b7c
Create Date: 2025-05-12 20:14:53.534263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71cea428a3f3'
down_revision: Union[str, None] = 'b1f6f69e7b7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bot_tokens', 'telegram_bot_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='ID Telegram бота',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bot_tokens', 'telegram_bot_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='ID Telegram бота',
               existing_nullable=True)
    # ### end Alembic commands ###
