"""add new table questions

Revision ID: a400166c5352
Revises: d145f82a1e27
Create Date: 2025-05-24 18:53:46.143998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a400166c5352'
down_revision: Union[str, None] = 'd145f82a1e27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Дата удаления (если используется мягкое удаление)'),
    sa.ForeignKeyConstraint(['question_id'], ['test_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('bot_tokens', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Дата удаления (если используется мягкое удаление)'))
    op.add_column('test_questions', sa.Column('order', sa.Integer(), nullable=True))
    op.add_column('test_questions', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Дата удаления (если используется мягкое удаление)'))
    op.drop_constraint('test_questions_bot_id_fkey', 'test_questions', type_='foreignkey')
    op.drop_column('test_questions', 'bot_id')
    op.add_column('test_types', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Дата удаления (если используется мягкое удаление)'))
    op.add_column('test_user_answers', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Дата удаления (если используется мягкое удаление)'))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Дата удаления (если используется мягкое удаление)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('test_user_answers', 'deleted_at')
    op.drop_column('test_types', 'deleted_at')
    op.add_column('test_questions', sa.Column('bot_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('test_questions_bot_id_fkey', 'test_questions', 'bot_tokens', ['bot_id'], ['id'])
    op.drop_column('test_questions', 'deleted_at')
    op.drop_column('test_questions', 'order')
    op.drop_column('bot_tokens', 'deleted_at')
    op.drop_table('test_answers')
    # ### end Alembic commands ###
