"""empty message

Revision ID: b1f6f69e7b7c
Revises: 3a221e665ff4
Create Date: 2025-05-12 15:48:28.967729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1f6f69e7b7c'
down_revision: Union[str, None] = '3a221e665ff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_tokens', sa.Column('telegram_bot_id', sa.Integer(), nullable=True, comment='ID Telegram бота'))
    op.add_column('bot_tokens', sa.Column('bot_username', sa.String(length=100), nullable=True, comment='Юзернейм Telegram бота'))
    op.create_unique_constraint(None, 'bot_tokens', ['telegram_bot_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bot_tokens', type_='unique')
    op.drop_column('bot_tokens', 'bot_username')
    op.drop_column('bot_tokens', 'telegram_bot_id')
    # ### end Alembic commands ###
