"""33 migration

Revision ID: d145f82a1e27
Revises: 71cea428a3f3
Create Date: 2025-05-15 21:37:32.530225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd145f82a1e27'
down_revision: Union[str, None] = '71cea428a3f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_id', sa.BigInteger(), nullable=False, comment='ID Telegram пользователя'))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True, comment='Активен ли пользователь'))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True, comment='Является ли пользователь администратором'))
    op.create_unique_constraint(None, 'users', ['telegram_id'])
    op.drop_column('users', 'height')
    op.drop_column('users', 'age')
    op.drop_column('users', 'email')
    op.drop_column('users', 'weight')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('gender', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('weight', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'telegram_id')
    # ### end Alembic commands ###
